# Import and Load Dataset

In [6]:
import pandas as pd

DATA_PATH = "../data/raw/ai_resume_screening.csv"

df = pd.read_csv(DATA_PATH)
df.head()

,years_experience,skills_match_score,education_level,project_count,resume_length,github_activity,shortlisted
0,6,84.7,Bachelors,7,234,158,No
1,3,59.1,Masters,5,502,77,No
2,12,100.0,Masters,12,753,381,Yes
3,14,66.8,High School,8,529,407,Yes
4,10,99.6,Bachelors,10,754,331,Yes

# Shape and Columns

In [7]:
df.shape, df.columns

((30000, 7),
 Index(['years_experience', 'skills_match_score', 'education_level',
        'project_count', 'resume_length', 'github_activity', 'shortlisted'],
       dtype='object'))

# Target Distribution

In [8]:
df["shortlisted"].value_counts(normalize=True)

shortlisted
Yes    0.698867
No     0.301133
Name: proportion, dtype: float64

# Basic Stats

In [9]:
df.describe()

,years_experience,skills_match_score,project_count,resume_length,github_activity
count,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000
mean,7.506567,73.682653,10.646267,572.584700,325.260667
std,4.624104,16.765909,4.634047,178.709918,159.951803
min,0.000000,0.500000,0.000000,150.000000,0.000000
25%,3.750000,62.100000,7.000000,441.000000,202.000000
50%,7.000000,74.300000,10.000000,574.000000,321.000000
75%,12.000000,86.500000,14.000000,709.000000,443.000000
max,15.000000,100.000000,25.000000,900.000000,842.000000

# Categorical Feature Inspection

In [10]:
df["education_level"].value_counts()

education_level
Bachelors      13461
Masters        10524
PhD             3024
High School     2991
Name: count, dtype: int64

## Dataset Overview

This dataset represents structured resume attributes used for automated screening.
The target variable `shortlisted` indicates whether a candidate passed initial screening.